### ISSUE TITLE
Crash when exporting the DP app

### ISSUE THREAD

**Issue by lolxnn** [zoogie/Frogminer#1]
I've followed the guide and i setted up steelminer, homebrews works as normal but this tool not it crashes whe i try to dump the Download Play app. 
![img_20181002_191929](https://user-images.githubusercontent.com/28827592/46365278-71a7d600-c678-11e8-8c58-649a7da5729a.jpg)

O3DS EUR 11.8

**Comment by zoogie** [comment]
Issues aren't really for tech support. Feel free to join this discord and they'll be able to help you out
https://discordapp.com/invite/C29hYvh

(3ds-assistance #1 or 3ds-assistance #2 channel)
